#!/bin/sh

cat <<EOF 
This will activate PearlHD-Skin matching your current resolution.

ATTENTION 
In order to do so vdr needs to be stopped. If you don't want 
that please press CTRL-C, else just press ENTER. 
EOF 
read

initctl stop vdr 
sleep 2 

DISPLAY=:1 /usr/bin/xwininfo -root >/tmp/xwininfo.out 2>/dev/null
if [ -f /tmp/xwininfo.out ]; then
  WIDTH=$(grep Width /tmp/xwininfo.out|tr -d ' '|cut -d ':' -f 2)
  if [ "$(dbget system.display.width)" != "$WIDTH" ]; then
    changed=1
    dbset "system.display.width=$WIDTH"
  fi
  HEIGHT=$(grep Height /tmp/xwininfo.out|tr -d ' '|cut -d ':' -f 2)
  if [ "$(dbget system.display.height)" != "$HEIGHT" ]; then
    changed=1
    dbset "system.display.height=$HEIGHT"
  fi
  if [ $changed -eq 1 ]; then
    signal-event display-resolution-changed
  fi
fi

initctl start vdr 

