#!/bin/bash

LOGFILE=/tmp/packagerebuilder.log
REASON="reb. vdr-1.7.16 unstable repo"
EMAIL="Holger Schvestka <hotzenplotz5@gmx.de>"
DISTRIBUTION=lucid
#DISTRIBUTION=natty

PACKAGES=(\
vdr-plugin-advchctrl \
  vdr-plugin-autostart \
  vdr-plugin-alcd \
  vdr-plugin-arghdirector \
  vdr-plugin-atmo \
  vdr-plugin-atscepg \
  vdr-plugin-autosort \
  vdr-plugin-avards \
  vdr-plugin-avolctl \
  vdr-plugin-bewegung \
  vdr-plugin-bgprocess \
  vdr-plugin-block \
  vdr-plugin-burn \
  vdr-plugin-calc \
  vdr-plugin-cdda \
  vdr-plugin-cdplayer \
  vdr-plugin-channellists \
  vdr-plugin-chanorg \
  vdr-plugin-cinebars \
  vdr-plugin-clock \
  vdr-plugin-control \
  vdr-plugin-devstatus \
  vdr-plugin-dbus \
  vdr-plugin-director \
  vdr-plugin-dummydevice \
  vdr-plugin-dynamite \
  vdr-plugin-dvd \
  vdr-plugin-dvdswitch \
  vdr-plugin-dxr3 \
  vdr-plugin-dyndvb \
  vdr-plugin-eepg \
  vdr-plugin-epgsearch \
  vdr-plugin-epgsync \
  vdr-plugin-extb \
  vdr-plugin-externalplayer \
  vdr-plugin-extrecmenu \
  vdr-plugin-femon \
  vdr-plugin-fepg \
  vdr-plugin-ffnetdev \
  vdr-plugin-filebrowser \
  vdr-plugin-freecell \
  vdr-plugin-fritzbox \
  vdr-plugin-games \
  vdr-plugin-graphlcd \
  vdr-plugin-graphtft \
  vdr-plugin-hdhomerun \
  vdr-plugin-image \
  vdr-plugin-imdbsearch \
  vdr-plugin-imonlcd \
  vdr-plugin-infosatepg \
  vdr-plugin-iptv \
  vdr-plugin-karaoke \
  vdr-plugin-lastfm \
  vdr-plugin-lcdproc \
  vdr-plugin-lcr \
  vdr-plugin-lircrc \
  vdr-plugin-live \
  vdr-plugin-loadepg \
  vdr-plugin-mailbox \
  vdr-plugin-markad \
  vdr-plugin-mcli \
  vdr-plugin-menuorg \
  vdr-plugin-mlcd \
  vdr-plugin-mldonkey \
  vdr-plugin-mlist \
  vdr-plugin-mousemate \
  vdr-plugin-mp3 \
  vdr-plugin-muggle \
  vdr-plugin-music \
  vdr-plugin-newsticker \
  vdr-plugin-noepgmenu \
  vdr-plugin-nordlichtsepg \
  vdr-plugin-osdpip \
  vdr-plugin-osdserver \
  vdr-plugin-osdteletext \
  vdr-plugin-osdtest256 \
  vdr-plugin-pilot \
  vdr-plugin-pim \
  vdr-plugin-pin \
  vdr-plugin-playlist \
  vdr-plugin-podcatcher \
  vdr-plugin-powermate \
  vdr-plugin-prefermenu \
  vdr-plugin-proxy \
  vdr-plugin-pvr350 \
  vdr-plugin-pvrinput \
  vdr-plugin-radio \
  vdr-plugin-radiolist \
  vdr-plugin-recstatus \
  vdr-plugin-reelchannelscan \
  vdr-plugin-remote \
  vdr-plugin-remoteosd \
  vdr-plugin-remotetimers \
  vdr-plugin-ripit \
  vdr-plugin-rotor \
  vdr-plugin-rssreader \
  vdr-plugin-scheduler \
  vdr-plugin-screenshot \
  vdr-plugin-serial \
  vdr-plugin-skinelchi \
  vdr-plugin-skinenigmang \
  vdr-plugin-skinsoppalusikka \
  vdr-plugin-sleeptimer \
  vdr-plugin-sndctl \
  vdr-plugin-softdevice \
  vdr-plugin-solitaire \
  vdr-plugin-span \
  vdr-plugin-spider \
  vdr-plugin-sportng \
  vdr-plugin-statusleds \
  vdr-plugin-streamdev \
  vdr-plugin-sudoku \
  vdr-plugin-surfer \
  vdr-plugin-suspendoutput \
  vdr-plugin-svdrposd \
  vdr-plugin-svdrpservice \
  vdr-plugin-systeminfo \
  vdr-plugin-targavfd \
  vdr-plugin-taste \
  vdr-plugin-text2skin \
  vdr-plugin-timeline \
  vdr-plugin-timersync \
  vdr-plugin-trayopen \
  vdr-plugin-trayopenng \
  vdr-plugin-ttxtsubs \
  vdr-plugin-tvm2vdr \
  vdr-plugin-tvonscreen \
  vdr-plugin-tvtv \
  vdr-plugin-undelete \
  vdr-plugin-upnp \
#  vdr-plugin-vbox \
  vdr-plugin-vcd \
  vdr-plugin-vdrc \
  vdr-plugin-vdrcd \
  vdr-plugin-vdrrip \
  vdr-plugin-vnsiserver \
  vdr-plugin-vodcatcher \
  vdr-plugin-vompserver \
  vdr-plugin-wapd \
  vdr-plugin-weather \
  vdr-plugin-weatherng 
  vdr-plugin-webvideo \
  vdr-plugin-wirbelscan \
  vdr-plugin-xine \
  vdr-plugin-xineliboutput \
  vdr-plugin-xmltv2vdr \
  vdr-plugin-xxvautotimer \
  vdr-plugin-yacoto \
  vdr-plugin-yaepghd \
  vdr-plugin-zaphistory \
  vdr-plugin-zappilot
)
rebuild_package() {
  echo "###### prozessing package $1 ######" | tee -a $LOGFILE
  TEMPDIR=/tmp/packagerebuilder.$$
  mkdir $TEMPDIR
  pushd $TEMPDIR >/dev/null
  apt-get source $1 2>>$LOGFILE >>$LOGFILE
  if [ $? -ne 0 ]; then
    echo "***** apt-get error *****" | tee -a $LOGFILE
  else
    pushd * >/dev/null
    HEADER=$(head -n 1 debian/changelog)
    NAME=$(echo $HEADER |cut -d ' ' -f 1)
    FULLVERSION=$(echo $HEADER |cut -d ' ' -f 2)
    FULLVERSION=${FULLVERSION:1:${#FULLVERSION}-2}
    LENGTH=${#FULLVERSION}
    for ((j=LENGTH-1; j > 0; j--))
    do
      if [ "${FULLVERSION:$j:1}" = "-" ]; then
        VERSION=${FULLVERSION:0:$j}
        RELEASE=${FULLVERSION:$j+1}
        break
      fi
    done
    RELEASE=$(($(expr "$RELEASE" : '\([0-9]*\)')+1))yavdr1
 
    echo $HEADER
    NEWHEADER="$NAME ($VERSION-$RELEASE) $DISTRIBUTION; urgency=low"
    echo $NEWHEADER
    (
      echo $NEWHEADER
      echo
      echo "  * $REASON"
      echo
      echo " -- $EMAIL  $(date -R)"
      echo
      cat debian/changelog
    ) >/tmp/changelog
    mv /tmp/changelog debian

    dpkg-buildpackage -sgpg -p/home/$USER/gpgscript -S -sa 2>>$LOGFILE >>$LOGFILE 
    if [ $? -ne 0 ]; then
      echo "***** dpkg-buildpackage error *****" | tee -a $LOGFILE
    else
      dput ppa:yavdr/unstable-vdr ../*.changes 2>>$LOGFILE >>$LOGFILE
#      dput ppa:hotzenplotz5/natty-yavdr ../*.changes 2>>$LOGFILE >>$LOGFILE
      [ $? -ne 0 ] && echo "***** dput error *****" | tee -a $LOGFILE
    fi
    popd >/dev/null
  fi
  popd >/dev/null
  [ -n "$TEMPDIR" ] && rm -rf $TEMPDIR
}

rm -f $LOGFILE

cnt=${#PACKAGES[@]}
for (( i = 0 ; i < cnt ; i++ ))
do
  rebuild_package ${PACKAGES[$i]}
done
