    <pvrmenu>
        <defaultguideview>2</defaultguideview>
        <hidevideolength>true</hidevideolength>
        <iconpath>/var/lib/vdr/channellogos/</iconpath>
        <infoswitch>true</infoswitch>
        <infotime>5</infotime>
        <infotimeout>true</infotimeout>
        <searchicons></searchicons>
    </pvrmenu>
