#!/bin/bash

# switch applications from vdr menu

for ARG in $@ ; do
   KEY="${ARG/=*}"
   VALUE="${ARG/*=}"

   case $KEY in
        standalone)
                 STANDALONE=$VALUE
                 ;;
        window)
                WINDOW=$VALUE
                ;;
        app)
                 APP=$VALUE
                 ;;
        *)
                 echo "unknown argument: $KEY"
                 ;;
    esac
done

# finished parsing arguments

STOP="/sbin/initctl stop --no-wait"

# minimum required arguments
if [ -z $STANDALONE ] || [ -z $APP ]; then
        echo "minimum required argument (standalone, app) not given, exit now ..."
        exit 0
fi

if [ ! -z $XDISPLAY ]; then
   OPTIONS="DISPLAY=:$XDISPLAY"
   export DISPLAY=:$XDISPLAY
else
   OPTIONS="DISPLAY=:1`dbget vdr.tempdisplay`"
   export DISPLAY=:1`dbget vdr.tempdisplay`
fi

if [ "x$STANDALONE" = "xyes" ]; then
    $STOP vdr-frontend
    /sbin/initctl start --no-wait toggle JOBNAME=$APP $OPTIONS STANDALONE=yes
else
    /sbin/initctl start --no-wait toggle JOBNAME=$APP $OPTIONS
fi


