#!/bin/bash

process-template --mode 755 /usr/bin/start-firefox
process-template --mode 755 /usr/bin/start-graphtft-fe
process-template --mode 755 /usr/bin/start-xbmc
process-template --mode 755 /usr/bin/start-xine
process-template --mode 755 /usr/bin/start-xineliboutput
process-template --mode 755 /usr/bin/start-xterm





