#!/bin/bash

process-template /etc/init/autofs.conf
process-template /etc/init/bootscreen.conf
process-template /etc/init/cleanTTY.conf
process-template /etc/init/dkms_autoinstaller.conf
process-template /etc/init/first-vdr-start.conf
process-template /etc/init/lirc.conf
process-template /etc/init/nodm.conf
process-template /etc/init/onshutdown.conf
process-template /etc/init/s3.conf
process-template /etc/init/setserial-minimal.conf
process-template /etc/init/usb-wakeup.conf
process-template /etc/init/vdr.conf
process-template /etc/init/vdr-frontend.conf


