#!/bin/bash

process-template /etc/init/autofs.conf
process-template /etc/init/bootscreen.conf
process-template /etc/init/cleanTTY.conf
process-template /etc/init/dkms_autoinstaller.conf
process-template /etc/init/first-vdr-start.conf
if [ -f /etc/init/lirc.conf ]; then
  rm -f /etc/init/lirc.conf
fi
process-template /etc/init/remoted.conf
process-template /etc/init/nodm.conf
process-template /etc/init/onshutdown.conf
process-template /etc/init/s3.conf
process-template /etc/init/s4.conf
process-template /etc/init/setserial-minimal.conf
process-template /etc/init/usb-wakeup.conf
process-template /etc/init/vdr.conf
process-template /etc/init/vdr-frontend.conf
process-template --mode 755 /usr/lib/vdr/config-loader
process-template --mode 755 /usr/lib/vdr/plugin-loader
process-template --mode 755 /usr/lib/vdr/commands-loader

