Document: vdr-plugin-jsonapi
Title: Debian vdr-plugin-jsonapi Manual
Author: <insert document author here>
Abstract: This manual describes what vdr-plugin-jsonapi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vdr-plugin-jsonapi/vdr-plugin-jsonapi.sgml.gz

Format: postscript
Files: /usr/share/doc/vdr-plugin-jsonapi/vdr-plugin-jsonapi.ps.gz

Format: text
Files: /usr/share/doc/vdr-plugin-jsonapi/vdr-plugin-jsonapi.text.gz

Format: HTML
Index: /usr/share/doc/vdr-plugin-jsonapi/html/index.html
Files: /usr/share/doc/vdr-plugin-jsonapi/html/*.html
