	<remote	device="MCE_via_iMON">
		<play>KEY_PLAY</play>
		<pause>KEY_PAUSE</pause>
		<stop>KEY_STOP</stop>
		<forward>KEY_FASTFORWARD</forward>
		<reverse>KEY_REWIND</reverse>
		<left>KEY_LEFT</left>
		<right>KEY_RIGHT</right>
		<up>KEY_UP</up>
		<down>KEY_DOWN</down>
		<select>#KEY_OK</select>
		<pageplus>KEY_CHANNELUP</pageplus>
		<pageminus>KEY_CHANNELDOWN</pageminus>
		<back>KEY_BACKSPACE</back>
		<menu>PreviousMenu</menu>
		<title>Guide</title>
		<info>KEY_INFO</info>
		<skipplus>KEY_SKIP</skipplus>
		<skipminus>KEY_REPLAY</skipminus>
		<display>Teletext</display>
		<start>WindowsMCE</start>
		<record>KEY_RECORD</record>
		<volumeplus>KEY_VOLUMEUP</volumeplus>
		<volumeminus>KEY_VOLUMEDOWN</volumeminus>
		<mute>KEY_MUTE</mute>
		<power>KEY_POWER</power>
		<myvideo>KEY_VIDEO</myvideo>
		<mymusic>KEY_AUDIO</mymusic>
		<mypictures>KEY_PHOTO</mypictures>
		<mytv>KEY_TV</mytv>
		<one>KEY_ONE</one>
		<two>KEY_TWO</two>
		<three>KEY_THREE</three>
		<four>KEY_FOUR</four>
		<five>KEY_FIVE</five>
		<six>KEY_SIX</six>
		<seven>KEY_SEVEN</seven>
		<eight>KEY_EIGHT</eight>
		<nine>KEY_NINE</nine>
		<zero>KEY_ZERO</zero>
		<star>Star</star>
		<hash>Hash</hash>
		<clear>KEY_DELETE</clear>
		<enter>KEY_ENTER</enter>
		<red>Red</red>
		<green>Green</green>
		<yellow>Yellow</yellow>
		<blue>Blue</blue>
	</remote>
