	<remote device="mceusb">
		<play>Play</play>
		<pause>Pause</pause>
		<stop>Stop</stop>
		<forward>Forward</forward>
		<reverse>Rewind</reverse>
		<left>Left</left>
		<right>Right</right>
		<up>Up</up>
		<down>Down</down>
		<select>OK</select>
		<pageplus>ChanUp</pageplus>
		<pageminus>ChanDown</pageminus>
		<back>Back</back>
		<menu>DVD</menu>
		<title>Guide</title>
		<info>More</info>
		<skipplus>Skip</skipplus>
		<skipminus>Replay</skipminus>
		<display>Aspect</display>
		<start>Home</start>
		<record>Record</record>
		<volumeplus>VolUp</volumeplus>
		<volumeminus>VolDown</volumeminus>
		<mute>Mute</mute>
		<power>Power</power>
		<myvideo>Videos</myvideo>
		<mymusic>Music</mymusic>
		<mypictures>Pictures</mypictures>
		<mytv>TV</mytv>
		<one>One</one>
		<two>Two</two>
		<three>Three</three>
		<four>Four</four>
		<five>Five</five>
		<six>Six</six>
		<seven>Seven</seven>
		<eight>Eight</eight>
		<nine>Nine</nine>
		<zero>Zero</zero>
		<star>Star</star>
		<hash>Hash</hash>
		<clear>Clear</clear>
		<enter>Enter</enter>
		<red>Red</red>
		<green>Green</green>
		<yellow>Yellow</yellow>
		<blue>Blue</blue>
		<teletext>Teletext</teletext>
	</remote>
