#!/bin/sh
case $1 in
     hibernate|suspend)
         echo "vdr is going to sleep"
         ;;
     thaw|resume)
         echo "vdr gets started again"
         service vdr start  
         ;;
     *)  echo "Irgendwer ruft mich total falsch auf."
         ;;
esac
