#!/bin/sh

if [ install = "$1" -o upgrade = "$1" ]; then 
   dpkg-divert --package yavdr-startup --add --rename \
      --divert /etc/init/usplash.conf.dontremove /etc/init/usplash.conf
   dpkg-divert --package yavdr-startup --add --rename \
      --divert /var/lib/vdr/plugins/xine/noSignal4x3.mpg.dontremove /var/lib/vdr/plugins/xine/noSignal4x3.mpg
   dpkg-divert --package yavdr-startup --add --rename \
      --divert /var/lib/vdr/plugins/xine/noSignal16x9.mpg.dontremove /var/lib/vdr/plugins/xine/noSignal16x9.mpg
   dpkg-divert --package yavdr-startup --add --rename \
      --divert /usr/share/libxine1-xvdr/nosignal.mpg.dontremove /usr/share/libxine1-xvdr/nosignal.mpg
   dpkg-divert --package yavdr-startup --add --rename \
      --divert /etc/issue.dontremove /etc/issue
   dpkg-divert --package yavdr-startup --add --rename \
      --divert /etc/vdr/plugins/externalplayer.conf.dontremove /etc/vdr/plugins/externalplayer.conf 
fi  

#DEBHELPER#

