epgsearch.AddSubtitleToTimerMode = 2
epgsearch.BlueKeyMode = 1
epgsearch.CheckConflictsAfterTimerProg = 0
epgsearch.CheckConflictsIntervall = 30
epgsearch.CheckConflictsIntervall2 = 15
epgsearch.CheckConflictsMinDuration = 0
epgsearch.CheckConflictsOnRecording = 0
epgsearch.CheckConflictsWithinLimit = 60
epgsearch.CheckTimerConflicts = 0
epgsearch.CheckTimerConflictsDays = 14
epgsearch.CheckTimerConflictsPriority = 0
epgsearch.DefLifetime = 99
epgsearch.DefMarginStart = 2
epgsearch.DefMarginStop = 10
epgsearch.DefPriority = 50
epgsearch.DefRecordingDir = 
epgsearch.DefSearchTemplateID = -1
epgsearch.FavoritesMenuTimespan = 24
epgsearch.HideMenu = 1
epgsearch.IgnorePayTV = 0
epgsearch.MailAddress = 
epgsearch.MailAddressTo = 
epgsearch.MailAuthPass = 
epgsearch.MailAuthUser = 
epgsearch.MailNotificationConflicts = 0
epgsearch.MailNotificationSearchtimers = 0
epgsearch.MailNotificationSearchtimersHours = 0
epgsearch.MailServer = 
epgsearch.MailUseAuth = 0
epgsearch.MailViaScript = 1
epgsearch.MainMenuEntry = 
epgsearch.MaxChannelMenuNow = 0
epgsearch.NoAnnounceWhileReplay = 0
epgsearch.NoConflMsgWhileReplay = 0
epgsearch.OnePressTimerCreation = 1
epgsearch.RedKeyMode = 0
epgsearch.ReplaceOrgSchedule = 1
epgsearch.ShowChannelGroups = 0
epgsearch.ShowChannelNr = 0
epgsearch.ShowDaySeparators = 0
epgsearch.ShowEmptyChannels = 0
epgsearch.ShowFavoritesMenu = 0
epgsearch.ShowProgress = 1
epgsearch.ShowRadioChannels = 1
epgsearch.StartMenu = 0
epgsearch.SVDRPPort = 6419
epgsearch.TimeIntervallFRFF = 30
epgsearch.TimerProgRepeat = 0
epgsearch.ToggleGreenYellow = 1
epgsearch.UpdateIntervall = 30
epgsearch.UseOkForSwitch = 0
epgsearch.UserMode1Description = 
epgsearch.UserMode1Time = 0
epgsearch.UserMode1UseIt = 0
epgsearch.UserMode2Description = 
epgsearch.UserMode2Time = 0
epgsearch.UserMode2UseIt = 0
epgsearch.UserMode3Description = 
epgsearch.UserMode3Time = 0
epgsearch.UserMode3UseIt = 0
epgsearch.UserMode4Description = 
epgsearch.UserMode4Time = 0
epgsearch.UserMode4UseIt = 0
epgsearch.UseSearchTimers = 0
epgsearch.UseVDRTimerEditMenu = 0
