#!/bin/bash

while getopts "d:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG 
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

DEV=/usr/bin/sundtekadapter -d $DEVID

/usr/bin/svdrpsend plug dynamite attd $DEV
