#!/bin/bash

#apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9A6F2FD5

cat <<EOF >/etc/apt/sources.list.d/yavdr.list
deb http://ppa.launchpad.net/yavdr/main/ubuntu natty main
deb http://ppa.launchpad.net/yavdr/unstable-vdr/ubuntu natty main
deb http://ppa.launchpad.net/yavdr/unstable-xbmc/ubuntu natty main
deb http://ppa.launchpad.net/yavdr/unstable-yavdr/ubuntu natty main

deb-src http://ppa.launchpad.net/yavdr/main/ubuntu natty main
deb-src http://ppa.launchpad.net/yavdr/unstable-vdr/ubuntu natty main
deb-src http://ppa.launchpad.net/yavdr/unstable-xbmc/ubuntu natty main
deb-src http://ppa.launchpad.net/yavdr/unstable-yavdr/ubuntu natty main
EOF

cat <<EOF >/etc/apt/sources.list.d/ubuntu-partner.list
deb http://archive.canonical.com/ubuntu natty partner
deb-src http://archive.canonical.com/ubuntu natty partner
EOF

cat <<EOF | apt-key add -
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.0.10

mI0ES6ftrQEEAPBGGmhTutCu9k2ZqTOcJSZEsSTVtDAL8MlDCG/P93O21DuwMzR83+fyRV//
RkeFFpDu8au0yIxgnjWi0KKws+WhiM3jixFOlJL02MGa5c8sG6UBZBIirsKBxr66zMxhwjoo
3TQ5QnwL2Tw5SZO6a/smiRr8+4PtBfw+YwuMwfVnABEBAAG0FExhdW5jaHBhZCBzdGFibGUt
dmRyiLYEEwECACAFAkun7a0CGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRAnKizhgQOz
YJoiBACKu6aHe4Axq35XTCCGamlAtlkbMK5Ghex5y4NSyjEZNHsCzMv+IKxenZ1lhiHvDYKW
UHBXRwd2qV+E66Mr3mxo96V1QiKHng2EqhZLLMFisAPO4/IlYRHIqTOpyrG0gpM1MkvXbR2Z
BE5o78RSDnN53Zpr3nc5J2veEJSbowC7Jg==
=Jk9g
-----END PGP PUBLIC KEY BLOCK-----
EOF
