#!/bin/bash


LINE=`grep 'epgsearch.SVDRPPort =' /var/lib/vdr/setup.conf`
PORT=${LINE//* = }

if [ "$PORT" = "2001" ]; then 
/sbin/stop vdr 
sed -i '/epgsearch.SVDRPPort =/ s/2001/6419/g' /var/lib/vdr/setup.conf
/sbin/start vdr
fi 
