#!/bin/bash
ORDER_CONF=/etc/vdr/plugins/order.conf
#ORDER_CONF=order.conf


append_plugin () {
  echo $1 >> $ORDER_CONF
}

enable_plugin () {
  if grep -q "$1\$" $ORDER_CONF; then
    sed -i -e "s/.*$1\$/$1/" $ORDER_CONF
  fi
}

disable_plugin () {
  if ! grep -q "$1\$" $ORDER_CONF; then
    append_plugin "-$1"
  else
    sed -i -e "s/.*$1\$/-$1/" $ORDER_CONF
  fi
}

if [ "$(dbget vdr.backend)" = "xineliboutput" ]; then
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  enable_plugin "xineliboutput"
  disable_plugin "xine"
  enable_plugin "iptv"
  enable_plugin "text2skin"
  enable_plugin "menuorg"
  enable_plugin "yaepghd"
  enable_plugin "extrecmenu"
  enable_plugin "suspendoutput"
  enable_plugin "imonlcd"
  enable_plugin "lcdproc"
  disable_plugin "dummydevice"
  disable_plugin "control"
  enable_plugin "*dynamite"
elif [ "$(dbget vdr.backend)" = "xine" ]; then
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  enable_plugin "xine"
  disable_plugin "xineliboutput"
  enable_plugin "iptv"
  enable_plugin "text2skin"
  enable_plugin "menuorg"
  enable_plugin "yaepghd"
  enable_plugin "extrecmenu"
  enable_plugin "suspendoutput"
  enable_plugin "imonlcd"
  enable_plugin "lcdproc"
  disable_plugin "dummydevice"
  disable_plugin "control"
  enable_plugin "*dynamite"
elif [ "$(dbget vdr.backend)" = "streaming" ]; then
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  enable_plugin "dummydevice"
  disable_plugin "xine"
  enable_plugin "xineliboutput"
  disable_plugin "lcdproc"
  disable_plugin "imonlcd"
  disable_plugin "iptv"
  disable_plugin "text2skin"
  disable_plugin "menuorg"
  disable_plugin "yaepghd"
  disable_plugin "extrecmenu"
  disable_plugin "suspendoutput"
  enable_plugin "control"
  enable_plugin "*dynamite"
elif [ "$(dbget vdr.backend)" = "hdff" || "$(dbget vdr.backend)" = "sdff" ]; then
  if [ "$(dbget vdr.backend)" = "sdff" ]; then
    enable_plugin "dvbsddevice"
    disable_plugin "dvbhddevice"
  else
    enable_plugin "dvbhddevice"
    disable_plugin "dvbsddevice"
  fi
  disable_plugin "dummydevice"
  disable_plugin "xine"
  disable_plugin "xineliboutput"
  enable_plugin "lcdproc"
  enable_plugin "imonlcd"
  enable_plugin "iptv"
  enable_plugin "text2skin"
  enable_plugin "menuorg"
  enable_plugin "yaepghd"
  enable_plugin "extrecmenu"
  enable_plugin "suspendoutput"
  enable_plugin "control"
  disable_plugin "*dynamite"
fi

# graphtft support
if [ "x$(dbget vdr.plugin.graphtft.enabled)" = "x1" ]; then
  enable_plugin "graphtft"
else
  disable_plugin "graphtft"
fi

# restart openbox if needed
if [ "$1" != "post-install" ]; then
  if [ "$(dbget vdr.frontend)" = "disabled" ]; then
    stop openbox &> /dev/null
  else
    start openbox || /bin/true
  fi
fi

# disable vdr if needed
if [ "$(dbget vdr.backend)" = "disabled" ]; then
  echo "manual" > /etc/init/vdr.override
else
  rm /etc/init/vdr.override
fi
