#!/bin/bash
ORDER_CONF=/etc/vdr/plugins/order.conf
#ORDER_CONF=order.conf

PLUGIN=`echo $3 | cut -f3 -d- -`

append_plugin () {
  echo $1 >> $ORDER_CONF
}

enable_plugin () {
  if grep -q "$1\$" $ORDER_CONF; then
    sed -i -e "s/.*$1\$/$1/" $ORDER_CONF
  else
    append_plugin "$1"
  fi
}

disable_plugin () {
  if ! grep -q "$1\$" $ORDER_CONF; then
    append_plugin "-$1"
  else
    sed -i -e "s/.*$1\$/-$1/" $ORDER_CONF
  fi
}

if [ "$2" = "enable" ]; then
  enable_plugin $PLUGIN
elif [ "$2" = "disable" ]; then
  disable_plugin $PLUGIN
  
  if [ "x$(dbget vdr.plugin.graphtft.enabled)" = "x1" -a "$PLUGIN" = "graphtft" ]; then
    dbset "vdr.plugin.graphtft.enabled=0"
  fi
fi
