#!/bin/bash

if [ ! -d /net.yavdr ]; then
   mkdir -p /net.yavdr
fi
USER=$(getent passwd 1000|cut -d ":" -f1)

process-template --data "user=$USER" /etc/init/firefox.conf
process-template /etc/init/xbmc.conf
process-template /etc/init/openbox.conf
process-template /etc/init/vdr-frontend.conf
process-template /etc/init/xbmc-exit.conf

