#!/bin/bash

############################################################################################################
# hardware detection for yavdr
# author: Marco Scholl <yavdr@marco-scholl.de>
############################################################################################################

# detect helper
check_pci() {
  lspci -nv | grep -q "Subsystem: $1"
}
check_pci2() {
  lspci -n | awk '{ print $3 }' | grep -q "$1"
}
check_usb() {
  lsusb | grep -q "$1"
}

############################################################################################################

# default channels.conf
SOURCE="IP"

# detect only one dvb tree
DRIVER=""

############################################################################################################
# erkenne erstmal geräte die mit beiden paketen laufen und mindest einen davon benötigen
# die DRIVER variable kann dann von nachfolgenden erkennungen überschrieben werden
############################################################################################################

# TT 6400 PCI
if check_pci "13c2:300a" || check_pci "13c2:300b"; then
  # ist kein treiber gewählt, so installiere den v4l
  SOURCE="SAT"
  DRIVER="v4l-dvb-dkms"
  dbset vdr.setup="custom"
  dbset vdr.frontend="disbaled"
  dbset vdr.backend="hdff"
  /usr/bin/signal-event change-frontend

# SD-FFs
elif check_pci2 "1131:7146" ; then
  dbset vdr.setup="custom"
  dbset vdr.frontend="disbaled"
  dbset vdr.backend="sdff"
  /usr/bin/signal-event change-frontend
fi

# TT 3600 USB
if check_usb "0b48:3007" || check_usb "0b48:300A"; then
  SOURCE="SAT"
  DRIVER="s2-liplianin-dkms"

# TeVii S470 - optional aber läuft wohl besser mit s2
elif check_pci "d470:9022"; then
  SOURCE="SAT"
  DRIVER="s2-liplianin-dkms"
fi

############################################################################################################
# erkenne nun nach priorität treiber vorraussetzungen
############################################################################################################
# erkenne s2-liplianin

# TeVii S660 USB
if check_usb "9022:d660"; then
  SOURCE="SAT"
  DRIVER="s2-liplianin-dkms"

# TeVii S480
elif check_pci "9022:d482" || check_pci "9022:d481"; then
  SOURCE="SAT"
  DRIVER="s2-liplianin-dkms"


# DVBWorld DVB-S2 PCIE2006
elif check_pci "1ADE:2032"; then
  SOURCE="SAT"
  DRIVER="s2-liplianin-dkms"

# dann erkenne v4l-dvb-dkms wenn kein s2

# Hauppauge WinTV-NOVA-HD-S2
elif check_usb "14f1:0800"; then
  SOURCE="SAT"
  DRIVER="v4l-dvb-dkms"
fi

#echo $DRIVER

# install driver
if [ -n "$DRIVER" ]; then
  apt-get install -y $DRIVER
fi

# detect: Sundtek Sticks
if check_usb "eb1a:5"; then
  apt-get install -y yavdr-hardware-sundtek
fi

# todo set channels
#echo $SOURCE
