#!/bin/bash


mkdir -p /var/lib/vdr/.xbmc/userdata/Database/



cat <<-! > /var/lib/vdr/.xbmc/userdata/guisettings.xml
<settings>
    <pvrmanager>
        <channelmanager></channelmanager>
        <channelscan></channelscan>
        <enabled>true</enabled>
        <resetdb></resetdb>
        <syncchannelgroups>true</syncchannelgroups>
    </pvrmanager>
    <pvrmenu>
        <defaultguideview>2</defaultguideview>
        <hidevideolength>true</hidevideolength>
        <iconpath></iconpath>
        <infoswitch>true</infoswitch>
        <infotime>5</infotime>
        <infotimeout>true</infotimeout>
        <searchicons></searchicons>
    </pvrmenu>
    <pvrplayback>
        <channelentrytimeout>0</channelentrytimeout>
        <playminimized>true</playminimized>
        <scantime>15</scantime>
        <signalquality>true</signalquality>
        <startlast>0</startlast>
        <switchautoclose>true</switchautoclose>
    </pvrplayback>
    <pvrrecord>
        <defaultlifetime>99</defaultlifetime>
        <defaultpriority>50</defaultpriority>
        <instantrecordtime>180</instantrecordtime>
        <marginstart>2</marginstart>
        <marginstop>10</marginstop>
    </pvrrecord>
</settings>
!

sqlite3  /var/lib/vdr/.xbmc/userdata/Database/TV12.db<<EOF
PRAGMA foreign_keys=OFF; BEGIN TRANSACTION; CREATE TABLE version (idVersion integer, iCompressCount integer); INSERT INTO "version" VALUES (12,0);
CREATE TABLE addon (id integer primary key, type text,name text, summary text, description text, stars integer,path text, addonID text, icon text, version text, changelog text, fanart text, author text);
CREATE TABLE addonextra (id integer, key text, value text);
CREATE TABLE repo (id integer primary key, addonID text,checksum text, lastcheck text);
CREATE TABLE addonlinkrepo (idRepo integer, idAddon integer);
CREATE TABLE disabled (id integer primary key, addonID text);
CREATE TABLE pvrenabled (id integer primary key, addonID text);
CREATE TABLE broken (id integer primary key, addonID text, reason text);
CREATE INDEX idxAddon ON addon(addonID);
CREATE INDEX idxAddonExtra ON addonextra(id);
CREATE UNIQUE INDEX ix_addonlinkrepo_1 ON addonlinkrepo ( idAddon, idRepo );
CREATE UNIQUE INDEX ix_addonlinkrepo_2 ON addonlinkrepo ( idRepo, idAddon );
CREATE UNIQUE INDEX idxDisabled ON disabled(addonID);
CREATE UNIQUE INDEX idxPVREnabled ON pvrenabled(addonID);
CREATE UNIQUE INDEX idxBroken ON broken(addonID);
COMMIT;
INSERT INTO "pvrenabled" VALUES(1,'pvr.vdr.vnsi');
EOF

chown -R vdr:vdr /var/lib/vdr/.xbmc

