#!/bin/bash

for INTERFACE in hdmi digital analog ; do
if [ $(LANG=C aplay -l | grep -i $INTERFACE | wc -l) -eq 1 ]; then
  SINK="$(LANG=C aplay -l | grep -i $INTERFACE)"
  # get the index id's
  CARD=${SINK//card } ; CARD=${CARD%%:*}
  DEVICE=${SINK//*device }; DEVICE=${DEVICE%%:*}

  # put them into db
  dbset system.hardware.alsa.${INTERFACE}.card=$CARD
  dbset system.hardware.alsa.${INTERFACE}.device=$DEVICE
elif [ $(LANG=C aplay -l | grep -i $INTERFACE | wc -l) -eq 4 ]; then
  ELD="`grep -e "monitor_present.*1$" /proc/asound/card?/eld* | cut -d":" -f1`"
  if [ "x$ELD" != "x" ]; then
    CARD="$(basename $(dirname $ELD))"; CARD=${CARD#card}
    ELD=${ELD#*\#} ; ELD=${ELD//.*}
    DEVICE=$(grep -e "^ *Device:.*" /proc/asound/card$CARD/codec\#${ELD})
    DEVICE=${DEVICE#*device=}

    # put them into db
    dbset system.hardware.alsa.${INTERFACE}.card=$CARD
    dbset system.hardware.alsa.${INTERFACE}.device=$DEVICE
  else 
    # we are totally lost and need to do some wild guessing
    dbset system.hardware.alsa.${INTERFACE}.card=1
    dbset system.hardware.alsa.${INTERFACE}.device=7
fi
done

