#!/bin/bash

for INTERFACE in hdmi digital analog ; do
if [ $(LANG=C aplay -l | grep -i $INTERFACE | wc -l) -eq 1 ]; then
  SINK="$(LANG=C aplay -l | grep -i $INTERFACE)"
  # get the index id's
  CARD=${SINK//card } ; CARD=${CARD%%:*}
  DEVICE=${SINK//*device }; DEVICE=${DEVICE%%:*}

  # put them into db
  dbset system.hardware.alsa.${INTERFACE}.card=$CARD
  dbset system.hardware.alsa.${INTERFACE}.device=$DEVICE
fi
done

