#!/bin/bash

LINE=$(xrandr -display :1 -q|grep "default connected")
X=$(echo $LINE | sed -e 's/[^0-9]*\([0-9]*\)x\([0-9]*\).*/\1/')
Y=$(echo $LINE | sed -e 's/[^0-9]*\([0-9]*\)x\([0-9]*\).*/\2/')

dbset system.x11.display.0.resolution.x=$X
dbset system.x11.display.0.resolution.y=$Y

if [ "x$(dbget system.x11.dualhead.enabled)" == "x1" ]; then
  LINE=$(xrandr -display :1.1 -q|grep "default connected")
  X=$(echo $LINE | sed -e 's/[^0-9]*\([0-9]*\)x\([0-9]*\).*/\1/')
  Y=$(echo $LINE | sed -e 's/[^0-9]*\([0-9]*\)x\([0-9]*\).*/\2/')

  dbset system.x11.display.1.resolution.x=$X
  dbset system.x11.display.1.resolution.y=$Y
else
  dbremove system.x11.display.1.resolution
fi