#!/bin/bash

pushd /var/cache/yavdr/upload >/dev/null

for i in "var/lib/vdr/remote.conf" "etc/vdr/diseqc.conf" "var/lib/vdr/channels.conf" "etc/lirc/lircd.conf" "var/lib/vdr/.xbmc/userdata/Lircmap.xml 
"; do
  if [ -f $i ]; then
    case $i in
      var/lib/vdr/remote.conf|etc/vdr/diseqc.conf)
        stop vdr 
        mv $i /$i
        chown vdr:vdr /$i
        start vdr
        echo "OK uploaded file /$i"
        ;;
      var/lib/vdr/channels.conf)
        mv $i /$i
        chown vdr:vdr /$i
        svdrpsend PLUG channellists LOAD 2>/dev/null >/dev/null
        echo "OK uploaded file /$i"
        ;;
      etc/lirc/lircd.conf)
        stop remoted
        mv $i /$i
        start remoted
        echo "OK uploaded file /$i"
        ;;
      var/lib/vdr/.xbmc/userdata/Lircmap.xml)        
        mv $i /$i
        chown vdr:vdr /$i
        echo "OK uploaded file /$i"
        ;;
      *)
        mv $i /$i
        ;;
    esac
    echo $i
  fi
done

popd >/dev/null
