#!/bin/bash

SERVICES="vdr nodm lirc dkms_autoinstaller inputlirc halevt tntnet"

for S in $SERVICES; do
  /usr/sbin/update-rc.d -f $S remove 2>/dev/null >/dev/null
  rm -f /etc/init.d/$S 2>/dev/null
done
