#!/bin/bash

if ! grep "vdr.*start-xterm" /etc/sudoers >/dev/null; then                                                       
  echo >>/etc/sudoers                                                                                           
  echo "# Added by yavdr-startup, don't remove" >>/etc/sudoers                                                  
  echo "vdr ALL=NOPASSWD: /usr/bin/start-xterm" >>/etc/sudoers                                                   
fi                                                             

if ! grep "vdr.*start" /etc/sudoers >/dev/null; then                                                       
  echo >>/etc/sudoers                                                                                           
  echo "# Added by yavdr-startup, don't remove" >>/etc/sudoers                                                  
  echo "vdr ALL=NOPASSWD: /sbin/start" >>/etc/sudoers                                                   
fi                                                             

if ! grep "vdr.*stop" /etc/sudoers >/dev/null; then                                                       
  echo >>/etc/sudoers                                                                                           
  echo "# Added by yavdr-startup, don't remove" >>/etc/sudoers                                                  
  echo "vdr ALL=NOPASSWD: /sbin/stop" >>/etc/sudoers                                                   
fi                                                             
