#!/bin/bash

if [ ! -d /net.yavdr ]; then
   mkdir -p /net.yavdr
fi
USER=$(getent passwd 1000|cut -d ":" -f1)

process-template --data "user=$USER" /etc/init/firefox.conf
process-template /etc/init/xbmc.conf
process-template /etc/init/openbox.conf
process-template /etc/init/taskbar.conf
process-template /etc/init/rsyslog-delay.conf
process-template --mode 755 /usr/lib/vdr/config-loader
process-template --mode 755 /usr/lib/vdr/plugin-loader
process-template --mode 755 /usr/lib/vdr/commands-loader
rm -f /etc/init/nodm.conf
rm -f /etc/init/lirc.conf
rm -f /etc/init/bootscreen.conf
rm -f /etc/init/cleanTTY.conf
rm -f /etc/init/logo.conf
rm -f /etc/cron.d/vdr
rm -f /etc/init/devilspie.conf
rm -f /etc/init/dvb-device.conf
rm -f /etc/init/dvb-driver-reload.conf
rm -f /etc/init/vdr-failed.conf
rm -f /etc/init/vdr-log-crashes.conf
rm -f /etc/init/yavdr-dvbmon.conf
