#!/bin/bash

if [ ! -d /net.yavdr ]; then
   mkdir -p /net.yavdr
fi

process-template /etc/init/firefox.conf
process-template /etc/init/xbmc.conf
process-template /etc/init/openbox.conf
process-template /etc/init/taskbar.conf
process-template --mode 755 /usr/lib/vdr/config-loader
process-template --mode 755 /usr/lib/vdr/plugin-loader
process-template --mode 755 /usr/lib/vdr/commands-loader
rm -f /etc/init/nodm.conf
rm -f /etc/init/lirc.conf
rm -f /etc/init/bootscreen.conf
rm -f /etc/init/cleanTTY.conf
rm -f /etc/init/logo.conf
rm -f /etc/cron.d/vdr
