#!/bin/sh

if [ remove = "$1" ]; then 
   dpkg-divert --package yavdr-base --remove --rename \
      --divert /etc/logrotate.conf.dontremove /etc/logrotate.conf
   dpkg-divert --package yavdr-base --remove --rename \
      --divert /etc/samba/smb.conf.dontremove /etc/samba/smb.conf
fi 

#DEBHELPER#
