#!/bin/sh
case $1 in
     hibernate|suspend)
         echo "vdr is going to sleep"
         service vdr-frontend stop
         service vdr stop
         service nodm stop
         ;;
     thaw|resume)
         echo "vdr gets started again"
         service nodm start
         service vdr-pre start  
         /sbin/initctl --quiet emit vdr-start
         ;;
     *)  echo "Irgendwer ruft mich total falsch auf."
         ;;
esac
