#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.
Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
if [ ${recordfail} = 1 ]; then
  set timeout=3
else
  set timeout=0
fi

