#!/bin/bash

process-template /etc/auto.net.yavdr
service autofs reload

# load default values and overrides from /etc/default/vdr 
. /usr/lib/vdr/config-loader

if [ -e /etc/auto.net.yavdr ]; then
    find $VIDEO_DIR/net -type l -exec rm {} \;
    for d in `cat /etc/auto.net.yavdr | awk '!/^#/ && /fstype/ {print $1}'`; do
        ln -s /net.yavdr/$d $VIDEO_DIR/net
    done
fi
touch $VIDEO_DIR/.update
chown vdr:vdr $VIDEO_DIR/.update
