#!/bin/bash

process-template /etc/auto.net.yavdr
service autofs reload

# load default values and overrides from /etc/default/vdr 
. /usr/lib/vdr/config-loader

if [ -e /etc/auto.net.yavdr ]; then
    for d in `cat /etc/auto.net.yavdr | awk '!/^#/ && /video/ {print $1}'`; do
        ln -s /net.yavdr/$d $VIDEO_DIR/net/$d
    done
fi

