#!/bin/sh

if [ install = "$1" -o upgrade = "$1" ]; then 
cat <<EOF >/etc/apt/sources.list.d/yavdr.list 
deb http://ppa.launchpad.net/phobie/ppa/ubuntu lucid main 
deb-src http://ppa.launchpad.net/phobie/ppa/ubuntu lucid main 
EOF
cat <<EOF | apt-key add -
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.0.10

mI0ESXbZJgEEAM18kNOVu3ZQ2drRIf0cMgEOboOH8UfUKS1X3USCRcDZi3J4AXrPwL5Q7Biq
rcFmZV9X/2PtRUeulRQZGArs+uaw4knyOkfz8FL65DpD3Rp83ZCHO9cd+IpmOdk9edRbvH+c
hm7AgrLUl8BxxetCepq/81+zffdZglEcTkcX8RoDABEBAAG0HExhdW5jaHBhZCBQUEEgZm9y
IFBlciBIYW5zZW6ItgQTAQIAIAUCSXbZJgIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJ
EI1m1eo18u5kvRQD/2sGb8lvDmYn/4Ilcf4IzXxa6fsHorDb+X12nVVOAssEORZoXNZGfGuK
jjKk4vNeF2c3YA+OKb05TdF9allf+bHWORmy2miUjjwpveIXiUwmoqeq+HkZRj5qBS/WD0Gy
wywbCVEKFOvJmv4iHx8JMQ5htP4K/Ad/2JK/Pyf90Mn9
=mHL3
-----END PGP PUBLIC KEY BLOCK-----
EOF

apt-get update
fi  

#DEBHELPER#

