#!/bin/bash

export DISPLAY=:1.1

GRAPHTFTFEOPTS="-W 800 -H 600 -n -r"
test -f /etc/default/graphtft-fe && . /etc/default/graphtft-fe

ps -A |grep -q -w graphtft-fe && exit
while  ! netcat -z localhost 2039; do sleep 1; done;

/usr/bin/graphtft-fe $GRAPHTFTFEOPTS -h localhost
