#!/bin/bash

export DISPLAY=:1
export HOME=/var/lib/vdr

XINELIBOUTPUTOPTS="--post tvtime:method=use_vo_driver --reconnect --fullscreen --audio=alsa --syslog"

if [ "x$(dbget system.hardware.nvidia.detected)" = "x1" ]; then                                                         
  vdpauinfo 2>/dev/null >/dev/null && XINELIBOUTPUTOPTS="$XINELIBOUTPUTOPTS --video=vdpau"
fi                                                                                                                      
       
while  ! netcat -z localhost 37890; do sleep 1; done;
/usr/bin/vdr-sxfe $XINELIBOUTPUTOPTS xvdr://127.0.0.1:37890
