#!/bin/sh                                                                                                               
                                                                                                                        
if [ remove = "$1" ]; then 
  /usr/bin/dpkg-trigger yavdr-addons-update
fi
