#!/bin/bash


while getopts "d:s:h:a:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG 
      ;;
    a)
      ADDRESS=$OPTARG 
      ;;
    h)
      HOST=$OPTARG 
      ;;
    s)
      SERIAL=$OPTARG 
      ;;
  esac
done

SKEY=`echo "$ADDRESS" | sed s/\\\\./_/g`
ID=`/opt/bin/mediaclient -e | grep "(${HOST})" | cut -f1 -d: | cut -f 2 -d " "`

if [ "X`dbget system.hardware.sundtek.stick.${SERIAL}_${SKEY}.mount`" = "X1" \
    -a -z "${ID}" ]; then
  /opt/bin/mediaclient --mount=$HOST:$DEVID
  ID=`/opt/bin/mediaclient -e | grep "(${HOST})" | cut -f1 -d: | cut -f 2 -d " "`
  dbset "system.hardware.sundtek.stick.${SERIAL}_${SKEY}.mounted=$ID"
fi