#!/bin/bash


while getopts "d:s:h:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG 
      ;;
    h)
      HOST=$OPTARG 
      ;;
    s)
      SERIAL=$OPTARG 
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [ "X`dbget system.hardware.sundtek.stick.$SERIAL.mount`" = "X1" ]; then
  /opt/bin/mediaclient --mount=$HOST:$DEVID
fi