#!/bin/bash


while getopts "d:s:h:a:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG 
      ;;
    a)
      ADDRESS=$OPTARG 
      ;;
    h)
      HOST=$OPTARG 
      ;;
    s)
      SERIAL=$OPTARG 
      ;;
  esac
done

if [ "X`dbget system.hardware.sundtek.stick.$SERIAL.mount`" = "X1" ]; then
  /opt/bin/mediaclient --mount=$HOST:$DEVID
fi