#!/bin/bash
ORDER_CONF=/etc/vdr/plugins/order.conf
#ORDER_CONF=order.conf


append_plugin () {
  echo $1 >> $ORDER_CONF
}

enable_plugin () {
  if grep -q "$1\$" $ORDER_CONF; then
    sed -i -e "s/.*$1\$/$1/" $ORDER_CONF
  fi
}

disable_plugin () {
  if ! grep -q "$1\$" $ORDER_CONF; then
    append_plugin "-$1"
  else
    sed -i -e "s/.*$1\$/-$1/" $ORDER_CONF
  fi
}

if [ "$(dbget vdr.frontend)" = "xineliboutput" ]; then
  enable_plugin "xineliboutput"
  disable_plugin "xine"
  enable_plugin "iptv"
  enable_plugin "text2skin"
  enable_plugin "menuorg"
  enable_plugin "yaepghd"
  enable_plugin "extrecmenu"
  enable_plugin "suspendoutput"
  disable_plugin "dummydevice"
elif [ "$(dbget vdr.frontend)" = "xine" ]; then
  enable_plugin "xine"
  disable_plugin "xineliboutput"
  enable_plugin "iptv"
  enable_plugin "text2skin"
  enable_plugin "menuorg"
  enable_plugin "yaepghd"
  enable_plugin "extrecmenu"
  enable_plugin "suspendoutput"
  disable_plugin "dummydevice"
elif [ "$(dbget vdr.frontend)" = "xbmc" ]; then
  enable_plugin "dummydevice"
  disable_plugin "xine"
  disable_plugin "xineliboutput"
  disable_plugin "iptv"
  disable_plugin "text2skin"
  disable_plugin "menuorg"
  disable_plugin "yaepghd"
  disable_plugin "extrecmenu"
  disable_plugin "suspendoutput"
fi
if [ "x$(dbget vdr.plugin.graphtft.enabled)" = "x1" ]; then
  enable_plugin "graphtft"
else
  disable_plugin "graphtft"
fi
