#!/bin/bash

#################################################################################
#                                                                               #
#   The following configuration file is generated automatically by the yaVDR    #
#     system. Don't change this file as every update of yaVDR will overwrite    #
#         the local changes. Instead put your required customizations           #
#       into /etc/yavdr/templates_custom/ based on the original templates       #
#                      under /usr/share/yavdr/templates.                        #
#                                                                               #
#   http://www.vdr-wiki.de/wiki/index.php/YaVDR-FAQ#Templating.2FCustomizing    #
#                                                                               #
#                                                                               #
#################################################################################

MAX="`dbget system.vdr.dvbmon.device_cnt`"
CURRENT="`ls /dev/dvb/adapter?/frontend? -1 | wc -l`"

#logger -t "dvbmon" "We got $CURRENT devices. We need $MAX ."

# if empty, then first start and we wait for udev to finish
# to count devices
if [ -n "$MAX" ]; then

# if the current number of devices matches the saved
# value, start vdr
  if [ "$CURRENT" = "$MAX" ]; then
     /sbin/initctl emit --no-wait dvb-devices-complete
     if [ -z "$JOB" ]; then
        # if JOB is empty, we get not started by upstart
        touch /tmp/.dvb-devices-complete
#        logger -t "dvbmon" "Starting vdr by UDEV."
     else
        touch /tmp/.dvb-first
#        logger -t "dvbmon" "Starting vdr by dvb-first."
     fi
  fi

  if [ "$CURRENT" -gt "$MAX" ]; then
    /sbin/initctl start --no-wait dvb-last DVBMON=1
#    logger -t "dvbmon" "We got a new device (New now $CURRENT)" 
  fi
fi
