#!/bin/bash
#
#  Copyright notice
#
#  (c) 2010 Gerald Dachs
#  All rights reserved
#
#  This script is part of the yaVDR project. yaVDR is
#  free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  The GNU General Public License can be found at
#  http://www.gnu.org/copyleft/gpl.html.
#  A copy is found in the textfile GPL.txt.
#
#  This script is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#

start_time=$(date +%s)

trap handle_timer ALRM

rm -rf /var/lock/.dvbmon.start_vdr_lock

max_dvb_devices=$(dbget "system.vdr.dvbmon.max_dvb_devices")
if [ -z $max_dvb_devices ]; then
  max_dvb_devices=10
  dbset "system.vdr.dvbmon.max_dvb_devices=$max_dvb_devices"
fi
interval=$(dbget "system.vdr.dvbmon.check_interval")
if [ -z $interval ]; then
  interval=5
  dbset "system.vdr.dvbmon.check_interval=$interval"
fi
prev_device_cnt=$(dbget "system.vdr.dvbmon.device_cnt")
if [ -z $prev_device_cnt ]; then
  prev_device_cnt=0
fi
prev_start_delay=$(dbget "system.vdr.dvbmon.start_delay")
if [ -z $prev_start_delay ]; then
  prev_start_delay=0
fi


start_vdr() {
  if mkdir /var/lock/.dvbmon.start_vdr_lock 2>/dev/null; then
    logger -i -s "$0 - trigger vdr start"
  else
    logger -i -s "$0 - vdr already started"
  fi
}

set_timer() { (sleep $1; kill -ALRM $$)& }

handle_timer() {
  logger -i -s "$0 - detection time of previous latest dvb device reached"
  start_vdr
}

if [ $prev_start_delay -gt 0 ]; then
  set_timer $prev_start_delay
fi

delay=0
old_start_delay=0
vdr_started=0
old_device_cnt=0

while [ 1 ]; do
  device_cnt=0
  i=0
  while [ $i -lt $max_dvb_devices ]; do
    creation_time=$(stat --printf="%Z" /dev/dvb/adapter$i/frontend0 2>/dev/null)
    if [ $? -eq 0 ]; then
      device_cnt=$(($device_cnt+1))
      delay=$(($creation_time-$start_time))
    fi
    i=$(($i+1))
  done
  if [ $vdr_started -eq 0 -a $device_cnt -gt 0 -a $device_cnt -ge $prev_device_cnt ]; then
    trap "" ALRM
    logger -i -s "$0 - previous device count reached"
    start_vdr
    vdr_started=1
  fi
  if [ $device_cnt -gt 0 -a $device_cnt -ne $old_device_cnt ]; then
    dbset "system.vdr.dvbmon.device_cnt=$device_cnt"
    logger -i -s "$0 - device count changed: detected $device_cnt device(s)"
    old_device_cnt=$device_cnt
  fi
  if [ $delay -gt 0 -a $delay -ne $old_start_delay ]; then
    dbset "system.vdr.dvbmon.start_delay=$delay"
    logger -i -s "$0 - device detected $delay seconds after start"
    old_start_delay=$delay 
  fi
    
  i=$interval
  while [ $i -gt 0 ]; do
    i=$(($i-1))
    sleep 1
  done
done
