#!/bin/sh                                                                                                               
                                                                                                                        
if [ remove = "$1" ]; then 
  /usr/bin/dpkg-trigger yavdr-addons-update
  rm -f /etc/init/semsix.conf
fi

#DEBHELPER#
