#!/usr/bin/perl -w

=head1 NAME

dh_installyavdr - prepares a package for yaVDR

=head1 SYNOPSIS

B<dh_installyavdr> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_installyavdr prepares a package for yaVDR

=cut

use strict;
use Debian::Debhelper::Dh_Lib;
inhibit_log();

init();

foreach my $package (@{$dh{DOPACKAGES}}) {
  autoscript($package,"postinst","postinst-yavdr");
}

=head1 SEE ALSO

L<debhelper(7)>

=head1 AUTHOR

Gerald Dachs <gda@dachsweb.de>

=cut
