#!/bin/sh

if  test $# = 0							\
 && test x"$SIGNAL_EVENT_NOTRIGGER" = x				\
 && test x"$DPKG_MAINTSCRIPT_PACKAGE" != x			\
 && dpkg-trigger --check-supported 2>/dev/null			\
 && dpkg --compare-versions "$DPKG_RUNNING_VERSION" ge '1.14.5ubuntu10~~'
then
	if dpkg-trigger --no-await yavdr-$1; then
		if test x"$SIGNAL_EVENT_TRIGGER_DEBUG" != x; then
			echo "signal-event: wrapper deferring $1 (trigger activated)"
		fi
		exit 0
	fi	
fi

exec /usr/bin/signal-event.real "$@"
