#!/bin/bash

<?cs if:system.sound.type == "hdmi" ?>
sed -i '/xineliboutput.Audio.Speakers =/ s/Pass Through/Stereo 2.0/g' /var/lib/vdr/setup.conf
<?cs /if ?>

<?cs if:system.sound.type == "passthrough" ?>
sed -i '/xineliboutput.Audio.Speakers =/ s/Stereo 2.0/Pass Through/g' /var/lib/vdr/setup.conf
<?cs /if ?>


