#!/bin/bash

EDID_LIST=edid.list

rm -f edid.bin*
rm -f X.log

/usr/bin/xinit /usr/bin/nvidia-xconfig -E X.log -- :2 vt10 -logverbose 6 -logfile X.log 2>/dev/null | sort |\
while read line; do
  if echo $line | grep -q "Wrote EDID for"; then
    name=$(echo $line | cut -d "\"" -f 2)
    file=$(echo $line | cut -d "\"" -f 4)
    if [ "$name"x != "$lastname"x ]; then
      echo -n $name, >>$EDID_LIST
      basename $file >>$EDID_LIST
      lastname=$name
    else
      rm -f $file
    fi
  fi
done

rm -f X.log
