#!/bin/bash

while getopts "d:s:h:a:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG
      ;;
    h)
      HOST=$OPTARG
      ;;
    a)
      ADDRESS=$OPTARG
      ;;
    s)
      SERIAL=$OPTARG
      ;;
  esac
done

SKEY=`echo "$ADDRESS" | sed s/\\\\./_/g`

LOCALID=`/usr/bin/sundtekadapter --serial=${SERIAL} --remoteonly -o id`

if [ -n "$LOCALID" ]; then
    DEV=`/usr/bin/sundtekadapter --serial=${SERIAL} --remoteonly -o frontend`

    if [ -n "$DEV" ]; then
      vdr-dbus-send /Plugins/dynamite plugin.SVDRPCommand string:'DETD' string:"$DEV"
      /opt/bin/mediaclient --unmount=$LOCALID
    fi

    /usr/bin/dbremove system.hardware.sundtek.frontend.$LOCALID
    /usr/bin/dbremove system.hardware.sundtek.stick.${SERIAL}_${SKEY}.mounted
fi
