#!/bin/bash

while getopts "d:s:h:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG 
      ;;
    h)
      HOST=$OPTARG 
      ;;
    s)
      SERIAL=$OPTARG 
      ;;
  esac
done

LOCALID=`/usr/bin/dbget system.hardware.sundtek.stick.$SERIAL.mounted`

if [ -n "$LOCALID" ]; then
    DEV=`/usr/bin/dbget system.hardware.sundtek.frontend.$LOCALID`
    
    if [ -n "$DEV" ]; then
      /usr/bin/svdrpsend plug dynamite detd $DEV
    fi
    
    /usr/bin/dbremove system.hardware.sundtek.frontend.$LOCALID
    /usr/bin/dbremove system.hardware.sundtek.stick.$SERIAL.mounted
fi