#!/bin/bash

while getopts "d:s:h:a:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG
      ;;
    h)
      HOST=$OPTARG
      ;;
    a)
      ADDRESS=$OPTARG
      ;;
    s)
      SERIAL=$OPTARG
      ;;
  esac
done

SKEY=`echo "$ADDRESS" | sed s/\\\\./_/g`

LOCALID=`/usr/bin/dbget system.hardware.sundtek.stick.${SERIAL}_${SKEY}.mounted`

if [ -n "$LOCALID" ]; then
    DEV=`/usr/bin/dbget system.hardware.sundtek.frontend.$LOCALID`
    
    if [ -n "$DEV" ]; then
      vdr-dbus-send /Plugins/dynamite plugin.SVDRPCommand string:'DETD' string:"$DEV"
    fi
    
    /usr/bin/dbremove system.hardware.sundtek.frontend.$LOCALID
    /usr/bin/dbremove system.hardware.sundtek.stick.${SERIAL}_${SKEY}.mounted
fi
