#!/bin/bash

logger "VIDEO_DIR=$VIDEO_DIR"

function checkmount()
{
    retry=30
    while [ $retry -gt 0 ]; do
        logger "testing for $1 ($retry)"
        sudo -u vdr touch $1/.update
        if [ $? -eq 0 ]; then
            logger "found $1"
            sudo -u vdr touch $VIDEO_DIR/.update
            $0 hold $1 &
	    break
        else
            logger "sleeping"
	    sleep 1
            retry=$(expr $retry - 1)
        fi
    done
}

function holdmount()
{
    while (true) do
        logger "testing for $1"
        sudo -u vdr touch $1/.update
        if [ $? -eq 0 ]; then
            logger "found $1"
            sleep 300
        else
            logger "sleeping"
	    sleep 60
        fi
    done
}

function checksync()
{
    if [ -e /etc/auto.net.yavdr ]; then
        logger "searching for video directories"
        for d in `cat /etc/auto.net.yavdr | awk '!/^#/ && /video/ {print $1}'`; do
            checkmount $VIDEO_DIR/net/$d
        done
    fi
}

logger "executing mount-loader"
if [ $# -eq 0 ]; then
    logger "entering async mode"
    export VIDEO_DIR
    /usr/lib/vdr/mount-loader sync &
else
    case "$1" in
    sync)
        checksync
    ;;
    hold)
        holdmount $2
    ;;
    esac
fi
