#!/bin/bash

logger "starting mount-loader"

# delayed start after vdr
sleep 15

# load default values and overrides from /etc/default/vdr 
. /usr/lib/vdr/config-loader

logger "VIDEO_DIR=$VIDEO_DIR"

function checkmount()
{
    retry=30
    while [ $retry -gt 0 ]; do
        logger "testing for $1 ($retry)"
        touch $1/.update
        if [ $? -eq 0 ]; then
            logger "found $1"
            touch $VIDEO_DIR/.update
	    break
        else
            logger "sleeping"
	    sleep 1
            retry=$(expr $retry - 1)
        fi
    done
}

logger "executing mount-loader"

if [ -e /etc/auto.net.yavdr ]; then
    logger "searching for video directories"
    for d in `cat /etc/auto.net.yavdr | awk '!/^#/ && /video/ {print $1}'`; do
        checkmount $VIDEO_DIR/net/$d
    done
fi

