#!/bin/bash

process-template /etc/vdr/plugins/iptv/vlcinput/3Sat.conf
process-template /etc/vdr/plugins/iptv/vlcinput/N-TV.conf
process-template /etc/vdr/plugins/iptv/vlcinput/NASA.conf

cat <<EOF >/var/lib/vdr/channels.conf
3Sat;IPTV:1:S=0|P=0|F=EXT|U=vlc2iptv|A=1:I:0:5:6:0:0:7:0:0:0
N-TV;IPTV:2:S=0|P=0|F=EXT|U=vlc2iptv|A=2:I:0:4:5:0:0:3:0:0:0
NASA;IPTV:3:S=0|P=0|F=EXT|U=vlc2iptv|A=3:I:0:2:3:0:0:1:0:0:0
EOF

chown vdr:vdr /var/lib/vdr/channels.conf
