#!/bin/bash

process-template /etc/init/performous.conf
process-template --owner=vdr --group=vdr /var/lib/vdr/.config/performous/config.xml
process-template /etc/fbpanel/yavdr
rm -f /usr/bin/start-performous

