#!/bin/sh                                                                                                               
                                                                                                                        
if [ remove = "$1" ]; then 
  /usr/bin/dpkg-trigger yavdr-addons-update
  process-template /etc/init/launcher.conf
  rm -f /etc/wmdrawer/mediathek
fi

#DEBHELPER#
