#!/bin/bash

# Vorgezogener fsck, falls ein MountCount +1 = MaxMountCount
# Die zu überprüfenden Laufwerke werden aus der /etc/fstab 
# liest (Spalte <pass> nicht 0)

for dev in $(grep -e "^[:blank:]*[^#].*[12][:blank:]*$" /etc/fstab |\
             tr -s '[:blank:]' | cut -d ' ' -f 1); do
	RunFsck="false"
	MountCount=`tune2fs -l $dev | grep "Mount count" | cut -c 27-`
	echo "$dev -> Mount count = $MountCount."
	MaxMountCount=`tune2fs -l $dev | grep "Maximum mount count" | cut -c 27-`
	echo "$dev -> Maximum mount count = $MaxMountCount."
	let MountCountZahl=$MountCount+1
	if [ $MountCountZahl -ge $MaxMountCount ]; then
		RunFsck="true"
		echo "$dev -> Running fsck is needed!"
		if [ $RunFsck == "true" ]; 	then
			touch /etc/mtab
			if [ $? -eq 0 ]; then
				echo "$dev -> File system is still mounted, skipping run of fsck!"
			else
			        # HIER KÖNNTE ETWAS AUF DEM DISPLAY ANGEZEIGT WERDEN...
				echo "$dev -> Now starting fsck..."
				STPID=$!
				fsck -C0 -y -f $dev
				echo "$dev -> Filesystemcheck is done."
			fi
		fi
	else
		echo "$dev -> No need to run fsck."
	fi
done #| logger -s -t force-fsck
