#!/bin/bash

while getopts "d:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG 
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

AVAHI_DAEMON_START=1
if [ -f /etc/default/avahi-daemon ]; then
  . /etc/default/avahi-daemon
fi

if [ "X${AVAHI_DAEMON_START}" = "X1" -a -n "$DEVID" -a "X`dbget system.hardware.sundtek.enablenetwork`" = "X1" ]; then
  SERIAL=`/usr/bin/sundtekadapter -d $DEVID -s`
  if [ "X`dbget system.hardware.sundtek.stick.$SERIAL.info.ip`" = "X" ]; then
    (
    cat <<EOF
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>
    <name replace-wildcards="yes">sundtek remote device $DEVID at %h</name>
    <service>
        <type>_dvb._tcp</type>
        <port>9234</port>
        <txt-record>id=$DEVID</txt-record>
        <txt-record>serial=$SERIAL</txt-record>
        <txt-record>ts=`date`</txt-record>
    </service>
</service-group>
EOF
    ) > /etc/avahi/services/sundtek-$DEVID.service
  fi
fi
