#!/bin/bash

while getopts "d:s:h:a:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG 
      ;;
  esac
done

DEV=`/usr/bin/sundtekadapter -d $DEVID`

vdr-dbus-send /Plugins/dynamite plugin.SVDRPCommand string:'ATTD' string:"$DEV"
