#!/bin/bash

killall -9 wmdrawer > /dev/null 2>&1
process-template /etc/init/pidgin.conf
process-template /etc/wmdrawer/web
process-template /etc/vdr/lifeguard.conf
rm -f /usr/bin/start-pidgin
start launcher
