#!/bin/bash

killall -9 wmdrawer > /dev/null 2>&1
process-template /etc/init/claws.conf
process-template /etc/wmdrawer/web
process-template /etc/vdr/lifeguard.conf
if [ -e /etc/default/locale ]; then 
. /etc/default/locale
fi 
process-template --owner=vdr --group=vdr /var/lib/vdr/plugins/menuorg.xml
start launcher
