#!/bin/sh

if [ install = "$1" -o upgrade = "$1" ]; then 
   dpkg-divert --package yavdr-utils --add --rename \
      --divert /etc/firefox/profile/prefs.js.dontremove /etc/firefox/profile/prefs.js
   dpkg-divert --package yavdr-utils --add --rename \
      --divert /etc/logrotate.conf.dontremove /etc/logrotate.conf
   dpkg-divert --package yavdr-utils --add --rename \
      --divert /etc/init/rsyslog.conf.dontremove /etc/init/rsyslog.conf
fi  

