#!/bin/bash

function checkmount()
{
    retry=3
    while [ $retry -gt 0 ]; do
        logger "testing for $1"
        sudo -u vdr touch $1/.update
        if [ $? -eq 0 ]; then
            logger "found $1"
	    break
        else
            logger "sleeping"
	    sleep 1
            retry=$(expr $retry - 1)
        fi
    done
}

function checksync()
{
    if [ -e /etc/auto.net.yavdr ]; then
        logger "searching for video directories"
        for d in `cat /etc/auto.net.yavdr | awk '!/^#/ && /video/ {print $1}'`; do
            checkmount $VIDEO_DIR/net/$d
        done
    fi
}

logger "executing mount-loader"
if [ $# -eq 0 ]; then
    logger "entering async mode"
    export VIDEO_DIR
    /usr/lib/vdr/mount-loader sync &
else
    case "$1" in
    sync)
        checksync
    ;;
    esac
fi
