#!/bin/bash

LOCAL_REPOSITORY=/var/cache/yavdr/local-repository

if [ -d $LOCAL_REPOSITORY ]; then
  pushd $LOCAL_REPOSITORY >/dev/null

  for i in *.deb; do 
    PACKAGES="$PACKAGES $(echo $i | cut -d'_' -f1 )"   
  done  

  if [ "x$PACKAGES" != "x" ]; then
    apt-get update
    apt-get -y install $PACKAGES
  fi

  popd >/dev/null
fi
